declare module "@strudel/core";
declare module "@strudel/codemirror";
declare module "@strudel/mini";
declare module "@strudel/tonal";
declare module "@strudel/webaudio";
declare module "@strudel/soundfonts";
declare module "@strudel/transpiler";
declare module "@fontsource/*";
declare module "superdough";
